2021-11-10 13:35:26,393 INFO    MainThread:32773 [wandb_setup.py:_flush():71] setting env: {}
2021-11-10 13:35:26,393 INFO    MainThread:32773 [wandb_setup.py:_flush():71] setting login settings: {}
2021-11-10 13:35:26,393 INFO    MainThread:32773 [wandb_setup.py:_flush():71] setting login settings: {'api_key': 'ae23566a860ef6134c6bd7d5cf4a0b72afa661b1'}
2021-11-10 13:35:26,393 INFO    MainThread:32773 [wandb_setup.py:_flush():71] setting login settings: {}
2021-11-10 13:35:26,393 INFO    MainThread:32773 [wandb_init.py:_log_setup():357] Logging user logs to /opt/ml/alchera-ai-challenge/baseline/torch_dev/wandb/run-20211110_133526-1h9slt98/logs/debug.log
2021-11-10 13:35:26,393 INFO    MainThread:32773 [wandb_init.py:_log_setup():358] Logging internal logs to /opt/ml/alchera-ai-challenge/baseline/torch_dev/wandb/run-20211110_133526-1h9slt98/logs/debug-internal.log
2021-11-10 13:35:26,393 INFO    MainThread:32773 [wandb_init.py:init():390] calling init triggers
2021-11-10 13:35:26,393 INFO    MainThread:32773 [wandb_init.py:init():395] wandb.init called with sweep_config: {}
config: {'batch': 16, 'epoch': 20, 'lr': 0.0001, 'seed': 21, 'save_capacity': 5, 'train_image_root': '../../train_dataset/train2014', 'train_mask_root': '../../train_dataset/train_mask', 'val_image_root': '../../train_dataset/val2014', 'val_mask_root': '../../train_dataset/val_mask', 'output_path': '../output', 'train_worker': 4, 'valid_worker': 4, 'test_worker': 4, 'wandb': True, 'wandb_project': 'alchera', 'wandb_entity': 'cv4', 'custom_name': 'test', 'TTA': True, 'test_batch': 4, 'csv_size': 256}
2021-11-10 13:35:26,393 INFO    MainThread:32773 [wandb_init.py:init():435] starting backend
2021-11-10 13:35:26,393 INFO    MainThread:32773 [backend.py:_multiprocessing_setup():94] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2021-11-10 13:35:26,413 INFO    MainThread:32773 [backend.py:ensure_launched():198] starting backend process...
2021-11-10 13:35:26,427 INFO    MainThread:32773 [backend.py:ensure_launched():203] started backend process with pid: 32876
2021-11-10 13:35:26,428 INFO    MainThread:32773 [wandb_init.py:init():444] backend started and connected
2021-11-10 13:35:26,430 INFO    MainThread:32773 [wandb_init.py:init():503] updated telemetry
2021-11-10 13:35:26,464 INFO    MainThread:32773 [wandb_init.py:init():533] communicating current version
2021-11-10 13:35:27,355 INFO    MainThread:32773 [wandb_init.py:init():538] got version response upgrade_message: "wandb version 0.12.6 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2021-11-10 13:35:27,356 INFO    MainThread:32773 [wandb_init.py:init():548] communicating run to backend with 30 second timeout
2021-11-10 13:35:27,605 INFO    MainThread:32773 [wandb_init.py:init():576] starting run threads in backend
2021-11-10 13:35:30,422 INFO    MainThread:32773 [wandb_run.py:_console_start():1693] atexit reg
2021-11-10 13:35:30,423 INFO    MainThread:32773 [wandb_run.py:_redirect():1567] redirect: SettingsConsole.REDIRECT
2021-11-10 13:35:30,423 INFO    MainThread:32773 [wandb_run.py:_redirect():1572] Redirecting console.
2021-11-10 13:35:30,425 INFO    MainThread:32773 [wandb_run.py:_redirect():1628] Redirects installed.
2021-11-10 13:35:30,425 INFO    MainThread:32773 [wandb_init.py:init():603] run started, returning control to user process
2021-11-10 13:35:30,425 INFO    MainThread:32773 [wandb_watch.py:watch():43] Watching
2021-11-10 13:35:34,466 INFO    MainThread:32773 [wandb_run.py:_atexit_cleanup():1663] got exitcode: 1
2021-11-10 13:35:34,466 INFO    MainThread:32773 [wandb_run.py:_restore():1635] restore
2021-11-10 13:35:36,944 INFO    MainThread:32773 [wandb_run.py:_wait_for_finish():1793] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 781
  total_bytes: 781
}

2021-11-10 13:35:37,201 INFO    MainThread:32773 [wandb_run.py:_wait_for_finish():1793] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 781
  total_bytes: 781
}

2021-11-10 13:35:37,628 INFO    MainThread:32773 [wandb_run.py:_wait_for_finish():1793] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 781
  total_bytes: 2843
}

2021-11-10 13:35:37,730 INFO    MainThread:32773 [wandb_run.py:_wait_for_finish():1793] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 781
  total_bytes: 5826
}

2021-11-10 13:35:37,831 INFO    MainThread:32773 [wandb_run.py:_wait_for_finish():1793] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 781
  total_bytes: 5826
}

2021-11-10 13:35:37,933 INFO    MainThread:32773 [wandb_run.py:_wait_for_finish():1793] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 5826
  total_bytes: 5826
}

2021-11-10 13:35:38,034 INFO    MainThread:32773 [wandb_run.py:_wait_for_finish():1793] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 5826
  total_bytes: 5826
}

2021-11-10 13:35:38,136 INFO    MainThread:32773 [wandb_run.py:_wait_for_finish():1793] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 5826
  total_bytes: 5826
}

2021-11-10 13:35:38,237 INFO    MainThread:32773 [wandb_run.py:_wait_for_finish():1793] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 5826
  total_bytes: 5826
}

2021-11-10 13:35:38,338 INFO    MainThread:32773 [wandb_run.py:_wait_for_finish():1793] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 5826
  total_bytes: 5826
}

2021-11-10 13:35:38,810 INFO    MainThread:32773 [wandb_run.py:_wait_for_finish():1793] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 5826
  total_bytes: 5826
}

2021-11-10 13:35:39,288 INFO    MainThread:32773 [wandb_run.py:_wait_for_finish():1793] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 5826
  total_bytes: 5826
}
local_info {
}

2021-11-10 13:35:40,431 INFO    MainThread:32773 [wandb_run.py:_append_files():2061] logging synced files
